nohup bash ./scripts/overallclassification/FEDformer.sh &
nohup bash ./scripts/overallclassification/FiLM.sh &
nohup bash ./scripts/overallclassification/iTransformer.sh &
nohup bash ./scripts/overallclassification/TimesNet.sh &
nohup bash ./scripts/overallclassification/Autoformer.sh &
nohup bash ./scripts/overallclassification/Crossformer.sh &
nohup bash ./scripts/overallclassification/DLinear.sh &
nohup bash ./scripts/overallclassification/Informer.sh &
nohup bash ./scripts/overallclassification/LightTS.sh &
nohup bash ./scripts/overallclassification/PatchTST.sh &
nohup bash ./scripts/overallclassification/Pyraformer.sh &
nohup bash ./scripts/overallclassification/Reformer.sh &
nohup bash ./scripts/overallclassification/Transformer.sh &
