nohup bash ./scripts/anxclassification/FEDformer.sh &
nohup bash ./scripts/anxclassification/FiLM.sh &
nohup bash ./scripts/anxclassification/iTransformer.sh &
nohup bash ./scripts/anxclassification/TimesNet.sh &
nohup bash ./scripts/anxclassification/Autoformer.sh &
nohup bash ./scripts/anxclassification/Crossformer.sh &
nohup bash ./scripts/anxclassification/DLinear.sh &
nohup bash ./scripts/anxclassification/Informer.sh &
nohup bash ./scripts/anxclassification/LightTS.sh &
nohup bash ./scripts/anxclassification/PatchTST.sh &
nohup bash ./scripts/anxclassification/Pyraformer.sh &
nohup bash ./scripts/anxclassification/Reformer.sh &
nohup bash ./scripts/anxclassification/Transformer.sh &