nohup bash ./scripts/depclassification/FEDformer.sh &
nohup bash ./scripts/depclassification/FiLM.sh &
nohup bash ./scripts/depclassification/iTransformer.sh &
nohup bash ./scripts/depclassification/TimesNet.sh &
nohup bash ./scripts/depclassification/Autoformer.sh &
nohup bash ./scripts/depclassification/Crossformer.sh &
nohup bash ./scripts/depclassification/DLinear.sh &
nohup bash ./scripts/depclassification/Informer.sh &
nohup bash ./scripts/depclassification/LightTS.sh &
nohup bash ./scripts/depclassification/PatchTST.sh &
nohup bash ./scripts/depclassification/Pyraformer.sh &
nohup bash ./scripts/depclassification/Reformer.sh &
nohup bash ./scripts/depclassification/Transformer.sh &
