nohup bash ./scripts/suisideclassification/FEDformer.sh &
nohup bash ./scripts/suisideclassification/FiLM.sh &
nohup bash ./scripts/suisideclassification/iTransformer.sh &
nohup bash ./scripts/suisideclassification/TimesNet.sh &
nohup bash ./scripts/suisideclassification/Autoformer.sh &
nohup bash ./scripts/suisideclassification/Crossformer.sh &
nohup bash ./scripts/suisideclassification/DLinear.sh &
nohup bash ./scripts/suisideclassification/Informer.sh &
nohup bash ./scripts/suisideclassification/LightTS.sh &
nohup bash ./scripts/suisideclassification/PatchTST.sh &
nohup bash ./scripts/suisideclassification/Pyraformer.sh &
nohup bash ./scripts/suisideclassification/Reformer.sh &
nohup bash ./scripts/suisideclassification/Transformer.sh &
